version: '3'
services:
   elasticsearch:
      image: elasticsearch:8.8.0
      ports: 
        - 9200:9200
        - 9300:9300
      environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Ajuste conforme necessário
      - xpack.security.enabled=false  # Desabilita a segurança para simplificar o teste